name: WAF setup

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-waf/**'
  workflow_dispatch:

env:
  TF_VERSION: "1.6.6"
  AWS_REGION: "ap-southeast-1"
  TF_WORKING_DIR: "./terraform-waf"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Destroys
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
