name: WAF setup

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment (dev, uat, prod)'
        required: true
        default: 'dev'

env:
  TF_VERSION: "1.6.6"
  AWS_REGION: "ap-southeast-1"
  TF_WORKING_DIR: "."

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Install Infracost
        run: |
          curl -sL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          echo "$HOME/.infracost/bin" >> $GITHUB_PATH

      - name: Infracost Breakdown
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          infracost breakdown --path=. \
            --terraform-var-file=environments/${{ github.event.inputs.env }}.tfvars \
            --usage-file=./infracost-usage.yml \
            --format table \
            --out-file infracost-report.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var-file="environments/${{ github.event.inputs.env }}.tfvars" -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
